spring.application.name=moviefinder
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=Root23@102006
spring.datasource.url=jdbc:mysql://localhost:8080/moviefinder
